### ISSUE TITLE
ImportError - missing files?

### ISSUE THREAD

**Issue by lpintes** [mohammad-suliman/visualStudioAddon#2] opened 2016-08-10 10:26 UTC
I just wanted to test the addon in VS 2015 Community. I just copied the deven.py from the addon. I received an import error immediately after opening VS on line 5:
from NVDAObjects.UIA import UIA, WpfTextView, Toast
Where are the imported files? I am using the latest next and the files are not available.
I also looked int NVDA sources and the files are not there.
Maybe you forgot to commit something?

**Comment by mohammad-suliman** [comment] 2016-08-10 16:58
thank you for the report! The issue is caused by recent change in NVDA to support Toasts in windows 10 red stone update.
I made a fix for the issue in the "beta" branch. You can switch to this branch and get the source from there. alternatively, you can replace all occurrences of "Toast" by "Toast_win10".
please let me know if there are any issues.
happy coding :)

**Comment by mohammad-suliman** [comment] 2016-08-10 18:31
sorry! the alternative is to replace "Toast" with "Toast_win8" class and not "Toast_win10".
I updated the beta branch accordingly.
something I forgot to mention, is that the changes which broke the add-on still in beta (master version) of NVDA. So if you decided to use the stable version, please use the master version of the add-on.

**Comment by mohammad-suliman** [comment] 2016-08-31 21:37
the changes in beta branch have been merged to master. The code in master will work for any version of NVDA. As a result, I am closing this issue.
please let me know if something goes wrong.

**Closed as completed by mohammad-suliman** 2016-08-31 21:37 UTC
